import Head from 'next/head'
import { useState } from 'react';

import { MdModeEditOutline, MdDone, MdDeleteForever } from 'react-icons/md';

export default function Home() {

  const [todos, setTodos] = useState([]);

  const [completedTasks, setCompletedTasks] = useState([]);

  const createTask = (e) => {
    e.preventDefault();
    const task = e.target[0].value;
    if (task === '') return;
    setTodos([...todos, task]);
    e.target[0].value = '';
    console.log(todos)
  }

  const validateTask = (index) => {
    const newTodos = [...todos];
    const completedTask = newTodos.splice(index, 1)[0];
    setTodos(newTodos);
    setCompletedTasks([...completedTasks, completedTask]);
  }

  const editTask = (index) => {
    const newTask = prompt('Modify your task');
    if (newTask !== null && newTask !== '') {
      const newTodos = [...todos];
      newTodos[index] = newTask;
      setTodos(newTodos);
    }
  }

  const deleteTask = (index) => {
    const newTodos = [...todos];
    newTodos.splice(index, 1);
    setTodos(newTodos);
  }

  const deleteCompletedTask = (index) => {
    const newCompletedTasks = [...completedTasks];
    newCompletedTasks.splice(index, 1);
    setCompletedTasks(newCompletedTasks);
  };


  return (
    <>
      <Head>
        <title>TODO-App</title>
        <meta name="description" content="TODO-App, generated by NextJS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="container">
          <h1>TODO LIST</h1>
          <p>This website is not responsive...yet</p>

          <div className="add-todo">
            <h2>Add Task</h2>
            <form method='POST' onSubmit={createTask}>
              <input type="text" placeholder="Add a new task..." />
              <button>Add</button>
            </form>
          </div>

          <div className="todos">
            <h2>Todo</h2>
            <ul className='todos-list'>
              {todos.map((todo, index) => (
                <li key={index}>
                  <span>{todo}</span>
                  <div className='actions-container'>
                    <button className='actions-buttons' onClick={() => editTask(index)}><MdModeEditOutline id='edit-icon' /></button>
                    <button className='actions-buttons' onClick={() => validateTask(index)}><MdDone id='done-icon' /></button>
                    <button className='actions-buttons' onClick={() => deleteTask(index)}><MdDeleteForever id='delete-icon' /></button>

                  </div>
                </li>
              ))}
            </ul>
          </div>

          <div className="completed-todo">
            <h2>Completed</h2>
            <ul className='completed-todo-list'>
              {completedTasks.map((todo, index) => (
                <li key={index}>
                  <span>{todo}</span>
                  <div className='actions-container'>
                    <button className='actions-buttons' onClick={() => deleteCompletedTask(index)}>
                      <MdDeleteForever id='delete-icon' />
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          </div>

        </div>
      </div >
    </>
  )
}
